#ifndef TOKENTYPE_H
#define TOKENTYPE_H

#include <string>

enum class TokenType {
    // SINGLE CHAR
    LEFT_PAREN, RIGHT_PAREN, LEFT_BRACE, RIGHT_BRACE,
    COMMA, DOT, SEMICOLON, COLON,

    // ONE OR TWO CHAR TOKENS
    COMMENT, BLOCK_COMMENT, PLUS, PLUS_PLUS, PLUS_EQ,
    MINUS, MINUS_MINUS, MINUS_EQ, SLASH, SLASH_EQ, STARR, STARR_EQ,
    EQUAL, EQUAL_EQ, GREATER, GREATER_EQ, LESS, LESS_EQ,
    PERCENT, PERCENT_EQ, BANG, BANG_EQ,
    AND, BIT_AND, OR, BIT_OR, XOR, ARROW,

    // LITERALS
    IDENTIFIER, STAR, NUMBER,

    // KEYWORDS
    LAUNCH, BIGBANG, MILKYWAY, MASS, FLUX, QUANTAM, NEBULA, TRUTH, STARLIGHT,
    VOIDNESS, VACUUM, BLACKHOLE, DARKMATTER, WARP, ROTATE,
    ORBIT, PHASE, ECLIPSE, SUPERNOVA, STARPATH, BLACKVOID,
    MOON, SHINE, GALAXY, EARTH, CONSTELLATION, CONSTRUCT,
    DEORBIT, SHIELD, RECOVER, EJECT, OPEN, CORE, ORBITSHIELD,

    // SPECIAL
    END_OF_FILE, NEW_LINE, ERROR
};


#endif
